version: "3"

services:
  redis_db:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["--save", "1", "1"]

  gene_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: gene_api:1.0
    container_name: gene-api-app
    ports:
      - "5000:5000"
    environment:
      REDIS_IP: 'redis_db'
    command: ["python", "src/api.py"]

  gene_worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: gene_worker:1.0
    container_name: gene-api-worker
    environment:
      REDIS_IP: 'redis_db'
    command: ["python", "src/worker.py"]
